services:

  app:
    build: .
    command: tail -f /dev/null 
    volumes:
      - ./:/workspace:cached

  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: devteds@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: devteds      
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres:12.19
    restart: always          
    environment: 
      POSTGRES_USER: devtedsuser
      POSTGRES_PASSWORD: devtedspass
      POSTGRES_DB: demodb
    volumes:                 
      - pg-data:/var/lib/postgresql/data

    # POSTGRES_HOST_AUTH_METHOD: "trust"
    # PGHBA_CONF_CONTENT: |
    #   host    all             all             0.0.0.0/0               md5    
    # - ./pgdata:/var/lib/postgresql/data
      # host    all             all             0.0.0.0/0               trust

volumes:
  pgadmin-data:
  pg-data:
